### ISSUE TITLE
1.20.1 versiyon

### ISSUE THREAD

**Issue by Rogenar** [Darkhax-Minecraft/Bed-Benefits#10]
When will version 1.20.1 of this mod come?

**Comment by Darkhax** [comment]
An update is coming soon. GitHub is for reporting bugs or errors, not asking for updates.

**Comment by Rogenar** [comment]
So where do we send our requests?

**Comment by Darkhax** [comment]
Feature requests are also fine on GitHub, but there's no need to send port/update requests to me or any other mod author. We know when a new MC update comes out and that our mod will immediately be broken for that version. Updates take time and real life often gets in the way. Creating port requests just leads to additional spam and distractions for authors.
