### ISSUE TITLE
leaving bed heals you even if you don´t sleep thru

### ISSUE THREAD

**Issue by ibimschder** [Darkhax-Minecraft/Bed-Benefits#11]
if you just leave bed before sleeping thru you still get healed making this a infinite heal glitch

**Comment by Darkhax** [comment]
Could you please provide more information? I am specifically looking for the Minecraft version, mod version, and what mod loader you're using.

**Comment by ibimschder** [comment]
Minecraft Version : 1.19.2
Mod version : 9.1.2
Mod Loader : Forge

Edit:
And i tested right now if it was another mod that conflicted but it wasn´t another mod that made the problem. 
with version 9.1.3 i also had the same problem

**Comment by Darkhax** [comment]
Thanks, I was able to find where the issue is in the mod's code. I haven't had time to release an update but it should be in the next day or two.

**Comment by ibimschder** [comment]
Ok thanks a lot for the help

**Comment by Darkhax** [comment]
This issue has now been fixed for 1.19.2 in version [9.2.5](https://www.curseforge.com/minecraft/mc-mods/bed-benefits/files/4744861). Fixes for 1.19.4 and 1.20.1 are also in the works.
