### ISSUE TITLE
[Request] Compatibility with Hourglass

### ISSUE THREAD

**Issue by Nycto97** [Darkhax-Minecraft/Bed-Benefits#12]
Would it be possible from your end to add compatibility between Bed Benefits and [Hourglass](https://www.curseforge.com/minecraft/mc-mods/hourglass)?

Currently, having the 2 mods installed, causes Bed benefits to not heal the player.

I'm on 1.19.2, I don't know if other versions are compatible.

Kind regards,
Nycto

**Comment by Darkhax** [comment]
Hi, I think it may be up to the Hourglass mod to add compatibility although if the dev thinks I can change anything on my end I am open to that. What version were you using? If you're on 9.2.5 it may be worth rolling back to 9.1.3. That update changed how player sleep is detected and it's possible the old code may be more compatible with Hourglass.

**Comment by Nycto97** [comment]
I was playing on 9.2.5. After testing I can say that 9.1.3 indeed heals the player with Hourglass installed.
Thank you for your recommendation. I'll stick with 9.1.3 for now until something changes to either Bed Benefits or Hourglass.

Also just found out BB is only required on server :) I always thought this was needed on both.

**Comment by Nycto97** [comment]
Seems like Hourglass didn't got updated in over a year. Saw an issue on The Aether repo where someone was mentioning Hourglass. Someone else recommended [Better Days](https://www.curseforge.com/minecraft/mc-mods/betterdays) mod (fork of Hourglass).

I might test some of these days to see if 9.2.5 works with Better Days.
