### ISSUE TITLE
Sleep Percentage Compatibility

### ISSUE THREAD

**Issue by cjh15hub** [Darkhax-Minecraft/Bed-Benefits#13]
Can the mod effect the player if the sleep percent isn't met? Meaning if the player interacts with the bed, but night doesn't pass due to not having enough players sleeping, does any of the mod take effect? I'm looking to make a multi-player server where sleeping to pass the night is disabled.

**Comment by Darkhax** [comment]
Hello, this used to be possible but it was due to a bug in the mod that I recently patched. While I could add a config option to undo that patch it is not an intentional feature and would have other related bugs and balance issues.
