### ISSUE TITLE
Healing by getting in and out of bed

### ISSUE THREAD

**Issue by Aceplante** [Darkhax-Minecraft/Bed-Benefits#15]
Effects are also cleared simply by getting in and out of bed

Forge 1.20.1

**Comment by Aceplante** [comment]
Appears to be the same issue from #11

**Comment by Darkhax** [comment]
Thank you for reminding me about this. It looks like I forgot to upload the fix for newer versions. I will get those out today.

**Comment by Darkhax** [comment]
This should now be fixed on 1.19.4, 1.20.1, and 1.20.4.

**Comment by Aceplante** [comment]
Edit: any chance it can be ported to 1.18.2 as well?

**Comment by Darkhax** [comment]
Sure, but it will take me a little while before I can get to it.

**Comment by Darkhax** [comment]
A build for 1.18.2 has been pushed and is awaiting approvals on all the platforms.

**Comment by Aceplante** [comment]
still happens on 1.18, latest version
