### ISSUE TITLE
[CRASH] Crash after waking up/leaving bed

### ISSUE THREAD

**Issue by MarijnIsN00B** [Darkhax-Minecraft/Bed-Benefits#16]
### Minecraft Version

1.16.5

### Mod Version

5.0.5

### Mod Loader

Forge

### What environment are you running the mod in?

Client

### Issue Description

My game crashes every time I wake up or leave a bed ingame

### Crash Log

https://mclo.gs/ifPGzdo

### Are you doing anything weird?

Waking up at a reasonable time is weird for me ig

**Comment by Darkhax** [comment]
Hello, the log file you uploaded doesn't show that the game has crashed. Is it possible that you uploaded the wrong log file or that you missed a bit of the text?

**Comment by MarijnIsN00B** [comment]
Sorry the logs were too long so it got cut off, heres the one with the crash https://mclo.gs/w5ST6e1

**Comment by Darkhax** [comment]
Do you have the mod Bookshelf installed? It's a required dependency. https://www.curseforge.com/minecraft/mc-mods/bookshelf

**Comment by MarijnIsN00B** [comment]
Didnt have it installed, that was the issue. Thanks lol
