### ISSUE TITLE
Crash on wake up

### ISSUE THREAD

**Issue by Tdarnell** [Darkhax-Minecraft/Bed-Benefits#2]
Crash log: https://paste.ee/p/JxNmv

net.darkhax.bedbenefits.BedBenefits.onPlayerWakeUp(BedBenefits.java:37)

If relevant I have natural regeneration game rule turned off for this world, I like the challenge! This mod seemed appropriate to add an early game heal

**Comment by Darkhax** [comment]
You're missing Bookshelf, it's a required dependency.

**Comment by Tdarnell** [comment]
> You're missing Bookshelf, it's a required dependency.

Ah makes sense, could you add that to the curse page description: https://www.curseforge.com/minecraft/mc-mods/bed-benefits

**Comment by Darkhax** [comment]
When you download a file it's included on the bottom of the page. https://www.curseforge.com/minecraft/mc-mods/bed-benefits/files/3112288
