### ISSUE TITLE
NOT A ISSUE JUST A QUESTION

### ISSUE THREAD

**Issue by TheeMrCheeky** [Darkhax-Minecraft/Bed-Benefits#8]
Saw bed benefits hasn't been update in almost a year on forge... but has been recently update on fabric? Is it dead on forge?

**Comment by Darkhax** [comment]
I believe you may be a bit confused. There are no official fabric versions of this mod. This mod is not dead though, I've just had to put it on the back burner while I focus on getting my other mods updated for 1.18+.

**Comment by TheeMrCheeky** [comment]
My apologies I relooked at the fabric version. Didn't notice the fine print ahaha. Understandable though!!

**Comment by Darkhax** [comment]
I've decided to port this mod to 1.18.2, and it's now using the MultiLoader system allowing both loaders to be supported simultaneously.

**Comment by TheeMrCheeky** [comment]
So you will have a official upload on fabric then? cause this is the one I am currently using on fabric https://www.curseforge.com/minecraft/mc-mods/bed-benefits-fabric

Also that is cool! I didn't know there was something that allowed both to be supported simultaneously

**Comment by Darkhax** [comment]
Yes, fabric is officially supported now. You can find the files [here](https://www.curseforge.com/minecraft/mc-mods/bed-benefits/files/all?filter-status=1&filter-game-version=2020709689%3A7499). No idea if the unofficial version you are using can be swapped out for this though.

**Comment by TheeMrCheeky** [comment]
Would prefer official version. :) Thanks man!! I will check it out!
