### ISSUE TITLE
Small Bug With Saturation

### ISSUE THREAD

**Issue by MikeTheBuddy** [Darkhax-Minecraft/Bed-Benefits#9]
I've noticed that the mod's mechanics have a feature where hunger is removed when healing and removing effects if necessary. I've noticed though that the saturation however doesn't decrease with the hunger, creating this weird effect of having saturation higher than your current hunger (Shouldn't be possible in normal play).

If possible, I think modifying the saturation if it's over the limit to the value the hunger was set to would be a good way to counteract it.

**Comment by Darkhax** [comment]
Thanks for letting me know about this. I've fixed the issue for 1.19.3, 1.19.2, and 1.18.2. The files will be on CurseForge soon.
